# MPLAB IDE generated this makefile for use with GNU make.
# Project: USB_Pedalog_2010_12_23.mcp
# Date: Tue Dec 28 15:40:06 2010

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

Outputs/USB_Pedalog_2010_12_23.cof : Objects/main.o Objects/usb_descriptors.o Objects/usb_device.o Objects/usb_function_generic.o Objects/busyxlcd.o Objects/openxlcd.o Objects/putrxlcd.o Objects/putsxlcd.o Objects/wcmdxlcd.o Objects/writdata.o Objects/user.o Objects/max7219matt.o Objects/readaddr.o Objects/readdata.o Objects/setcgram.o Objects/setddram.o
	$(LD) /p18F4550 /l"C:\Program Files\Microchip\mplabc18\v3.37\lib" /k"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedal Power Monitor v2_Shunt_Version_BL" "rm18f4550 - MCHPUSB Bootload.lkr" "Objects\main.o" "Objects\usb_descriptors.o" "Objects\usb_device.o" "Objects\usb_function_generic.o" "Objects\busyxlcd.o" "Objects\openxlcd.o" "Objects\putrxlcd.o" "Objects\putsxlcd.o" "Objects\wcmdxlcd.o" "Objects\writdata.o" "Objects\user.o" "Objects\max7219matt.o" "Objects\readaddr.o" "Objects\readdata.o" "Objects\setcgram.o" "Objects\setddram.o" /u_CRUNTIME /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Outputs\USB_Pedalog_2010_12_23.cof" /M"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Outputs\USB_Pedalog_2010_12_23.map" /W

Objects/main.o : main.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/string.h USB/usb_common.h USB/usb_device.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/delays.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/ctype.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/xlcd.h max7219matt.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/spi.h main.c Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdarg.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stddef.h HardwareProfile\ -\ Matt\ Datalogger.h GenericTypeDefs.h USB/usb_ch9.h USB/usb_hal.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/limits.h usb_config.h USB/usb_hal_pic18.h USB/usb.h usb/usb_common.h usb/usb_ch9.h usb/usb_hal.h usb/usb_device.h USB/usb_function_generic.h user.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/pconfig.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "main.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\main.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/usb_descriptors.o : usb_descriptors.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/string.h USB/usb_common.h USB/usb_device.h usb_descriptors.c GenericTypeDefs.h Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdarg.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stddef.h usb_config.h USB/usb_ch9.h USB/usb_hal.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/limits.h USB/usb_hal_pic18.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "usb_descriptors.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\usb_descriptors.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/usb_device.o : usb_device.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/string.h usb/usb_common.h usb/usb_device.h usb_device.c GenericTypeDefs.h Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdarg.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stddef.h USB/usb_ch9.h USB/USB.h usb_config.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/limits.h usb/usb_ch9.h usb/usb_hal.h USB/usb_common.h USB/usb_hal_pic18.h USB/usb_hal.h USB/usb_device.h HardwareProfile.h HardwareProfile\ -\ Matt\ Datalogger.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "usb_device.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\usb_device.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/usb_function_generic.o : usb_function_generic.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/string.h USB/usb_common.h USB/usb_device.h GenericTypeDefs.h Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdarg.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stddef.h usb_config.h USB/usb_ch9.h USB/usb_hal.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/limits.h USB/usb_hal_pic18.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "usb_function_generic.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\usb_function_generic.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/busyxlcd.o : C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/busyxlcd.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/xlcd.h C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/busyxlcd.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "C:\Program Files\Microchip\mplabc18\v3.37\src\pmc_common\XLCD\busyxlcd.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\busyxlcd.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/openxlcd.o : C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/openxlcd.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/delays.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/xlcd.h C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/openxlcd.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "C:\Program Files\Microchip\mplabc18\v3.37\src\pmc_common\XLCD\openxlcd.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\openxlcd.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/putrxlcd.o : C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/putrxlcd.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/xlcd.h C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/putrxlcd.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "C:\Program Files\Microchip\mplabc18\v3.37\src\pmc_common\XLCD\putrxlcd.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\putrxlcd.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/putsxlcd.o : C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/putsxlcd.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/xlcd.h C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/putsxlcd.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "C:\Program Files\Microchip\mplabc18\v3.37\src\pmc_common\XLCD\putsxlcd.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\putsxlcd.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/wcmdxlcd.o : C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/wcmdxlcd.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/xlcd.h C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/wcmdxlcd.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "C:\Program Files\Microchip\mplabc18\v3.37\src\pmc_common\XLCD\wcmdxlcd.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\wcmdxlcd.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/writdata.o : C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/writdata.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/xlcd.h C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/writdata.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "C:\Program Files\Microchip\mplabc18\v3.37\src\pmc_common\XLCD\writdata.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\writdata.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/user.o : user.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdio.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdlib.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/string.h USB/usb_common.h USB/usb_device.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/delays.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/xlcd.h max7219matt.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/spi.h user.c Compiler.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdarg.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stddef.h GenericTypeDefs.h HardwareProfile.h HardwareProfile\ -\ Matt\ Datalogger.h usb_config.h USB/usb_ch9.h USB/usb_hal.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/limits.h USB/usb_hal_pic18.h USB/usb.h usb/usb_common.h usb/usb_ch9.h usb/usb_hal.h usb/usb_device.h USB/usb_function_generic.h user.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/pconfig.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "user.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\user.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/max7219matt.o : max7219matt.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/spi.h max7219matt.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/string.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stdlib.h max7219matt.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/pconfig.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/stddef.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "max7219matt.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\max7219matt.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/readaddr.o : C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/readaddr.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/xlcd.h C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/readaddr.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "C:\Program Files\Microchip\mplabc18\v3.37\src\pmc_common\XLCD\readaddr.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\readaddr.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/readdata.o : C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/readdata.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/xlcd.h C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/readdata.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "C:\Program Files\Microchip\mplabc18\v3.37\src\pmc_common\XLCD\readdata.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\readdata.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/setcgram.o : C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/setcgram.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/xlcd.h C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/setcgram.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "C:\Program Files\Microchip\mplabc18\v3.37\src\pmc_common\XLCD\setcgram.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\setcgram.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

Objects/setddram.o : C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/setddram.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/xlcd.h C:/Program\ Files/Microchip/mplabc18/v3.37/src/pmc_common/XLCD/setddram.c C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18cxxx.h C:/Program\ Files/Microchip/mplabc18/v3.37/h/p18f4550.h
	$(CC) -p=18F4550 /i"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Usb" -I"C:\Program Files\Microchip\mplabc18\v3.37\h" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects" -I"E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." "C:\Program Files\Microchip\mplabc18\v3.37\src\pmc_common\XLCD\setddram.c" -fo="E:\Work\PRODUCTS\Microchip Solutions Backup C\USB Pedalog_2010_12_23\Objects\setddram.o" -D__DEBUG -mL -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

clean : 
	$(RM) "Objects\main.o" "Objects\usb_descriptors.o" "Objects\usb_device.o" "Objects\usb_function_generic.o" "Objects\busyxlcd.o" "Objects\openxlcd.o" "Objects\putrxlcd.o" "Objects\putsxlcd.o" "Objects\wcmdxlcd.o" "Objects\writdata.o" "Objects\user.o" "Objects\max7219matt.o" "Objects\readaddr.o" "Objects\readdata.o" "Objects\setcgram.o" "Objects\setddram.o" "Outputs\USB_Pedalog_2010_12_23.cof" "Outputs\USB_Pedalog_2010_12_23.hex"

